# Generated by Django 4.1.7 on 2023-04-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/static/event_default.jpg', upload_to='event_images/'),
        ),
    ]
