# Generated by Django 4.1.7 on 2023-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=8),
        ),
    ]
