# Generated by Django 4.1.7 on 2023-05-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
