# Generated by Django 4.1.7 on 2023-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(choices=[('Event', 'Event'), ('Comedy', 'Comedy'), ('CollegeEvent', 'CollegeEvent'), ('WorkShop', 'WorkShop'), ('Webinar', 'Webinar'), ('theater&art', 'theater&art')], default='Event', max_length=15),
        ),
    ]
