# Generated by Django 4.2.9 on 2024-02-04 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_booking_booked_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
