# Generated by Django 4.2.9 on 2024-03-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_alter_booking_booking_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(choices=[('Event', 'Event'), ('Comedy', 'Comedy'), ('CollegeEvent', 'CollegeEvent'), ('WorkShop', 'WorkShop'), ('Webinar', 'Webinar'), ('theater&art', 'theater&art')], default='Event', max_length=25),
        ),
    ]
