# Generated by Django 4.2.9 on 2024-03-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_alter_event_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
