# Generated by Django 4.1.7 on 2023-04-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Organizer', 'Organizer'), ('Customer', 'Customer')], default='Customer', max_length=10),
        ),
    ]
